Assignment1

In [ ]:
#question 1
arr = np.array([0]*4)
print("Array: ",arr)

Array:  [0 0 0 0]


In [ ]:
#question 2
ran = np.random.randint(0,10,6)
print("Array: ",ran)

Array:  [4 9 0 0 5 2]


In [ ]:
#question 3
arr1 = np.arange(10,50)
print("Array: ",arr1)
print("Number of elements: ",len(arr1))
print("Shape of the array: ",arr1.shape)
print("Dimension of array: ", arr.ndim)
print("Data type of array: ", arr.dtype)

Array:  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Number of elements:  40
Shape of the array:  (40,)
Dimension of array:  1
Data type of array:  int64


In [ ]:
#problem 4
arr2 = np.array([0]*10)
print(arr2)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
arr3 = np.ones([3,3])
print(arr3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr4 = np.eye(4)
print(arr4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr = np.arange(5,50,5)
print(arr)

[ 5 10 15 20 25 30 35 40 45]


In [ ]:
#problem 5
arr = np.arange(0,24)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
reshape1 = arr.reshape(4,6)
print("the reshaped of the matrix:",reshape1)
print("Shape of the matrix: ",reshape1.shape)
print("Dimension of the matrix: " ,reshape1.ndim)


the reshaped of the matrix: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Shape of the matrix:  (4, 6)
Dimension of the matrix:  2


In [ ]:
reshape2 = arr.reshape(6,4)
print("the reshaped of the matrix: " ,reshape2)
print("the shape of the matrix: " ,reshape2.shape)
print("the dimension of the matrix:",reshape2.ndim)

the reshaped of the matrix:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
the shape of the matrix:  (6, 4)
the dimension of the matrix: 2


In [ ]:
reshape3 = arr.reshape(2,3,4)
print("reshaped matrix:",reshape3)
print("shape of the matrix: ",reshape3.shape)
print("the dimension of the matrix:",reshape3.ndim)

reshaped matrix: [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
shape of the matrix:  (2, 3, 4)
the dimension of the matrix: 3


In [ ]:
#problem 6
arr = np.array([78,85,92,67,88,73,95,81])
print("the first element is: ",arr[0])
print("The last element is: " ,arr[-1])
print("The 3rd element is: ",arr[2])
print("The first 4 elements of the array are:",arr[:5])
print("The last three elements of the array are: ",arr[-3:])

the first element is:  78
The last element is:  81
The 3rd element is:  92
The first 4 elements of the array are: [78 85 92 67 88]
The last three elements of the array are:  [73 95 81]


In [ ]:
#problem 7
a = np.array([10,20,30,40,50])
b = np.array([5,10,15,20,25])

print("the addition of 2 arrays is: ", a+b)
print("the subtraction of two arrays is: ", a-b)
print("the multiplication of two arrays is: ", a*b)
print("the division of two arrays is: ", a/b)
print("the suqre of every element of a is: ",a**2)

the addition of 2 arrays is:  [15 30 45 60 75]
the subtraction of two arrays is:  [ 5 10 15 20 25]
the multiplication of two arrays is:  [  50  200  450  800 1250]
the division of two arrays is:  [2. 2. 2. 2. 2.]
the suqre of every element of a is:  [ 100  400  900 1600 2500]


In [ ]:
#problem 8
salary = np.array([25000,32000,28000,45000,50000,38000,42000,30000])
print("the sum of total slaries: " ,np.sum(salary))
print("the average salary given: ", np.mean(salary))
print("the maximum salary given: ",np.max(salary))
print("the minimum salary given: ",np.min(salary))
print("the median salary given: " , np.median(salary))
print("the standard deviation of the salary: ",np.std(salary))


the sum of total slaries:  290000
the average salary given:  36250.0
the maximum salary given:  50000
the minimum salary given:  25000
the median salary given:  35000.0
the standard deviation of the salary:  8317.902379807063


In [ ]:
#problem 9 = incomplete
marks = np.array([45,78,89,32,67,90,55,76,41,84])

print(marks[marks>75])
print(len(marks[marks<50]))


[78 89 90 76 84]
3


In [ ]:
#problem 10 = IMP
marks = np.array([
    [80,75,72],
    [65,70,72],
    [88,92,85],
    [55,60,58]
])

print("total marks of each student:",np.sum(marks,axis=1))
print("total marks of each subject:",np.sum(marks,axis=0))
print("the average marks of each student:",np.mean(marks,axis=1))#axis = 1 means row
print("the average marks of each subject:",np.mean(marks,axis=0))#axis =0 means colum
print("the maximum marks of each student:",np.max(marks,axis=1))
print("the maximum marks of each subject:",np.max(marks,axis=0))

total marks of each student: [227 207 265 173]
total marks of each subject: [288 297 287]
the average marks of each student: [75.66666667 69.         88.33333333 57.66666667]
the average marks of each subject: [72.   74.25 71.75]
the maximum marks of each student: [80 72 92 60]
the maximum marks of each subject: [88 92 85]


In [ ]:
#problem 11
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print("Addition of a and b", a+b)
print("element wise multiplication: ",a.dot(b))
print("Matrix multiplication: ", a*b)
print("The transpose of a: ", a.T)

Addition of a and b [[ 6  8]
 [10 12]]
element wise multiplication:  [[19 22]
 [43 50]]
Matrix multiplication:  [[ 5 12]
 [21 32]]
The transpose of a:  [[1 3]
 [2 4]]


In [ ]:
#problem 12
temp = np.array([31,32,33,35,36,34,32,30,29,31,33,35,37,36])
print("The mean temerature: ", np.mean(temp))
print("the maximin temperature: ", np.max(temp))
print("the minimum temperature: ", np.min(temp))
meanTemp = np.mean(temp)
print("the number of days above average temperature: ",len(temp[temp> meanTemp]))
print("the difference between maximun and minimum temperature is: ",np.max(temp)-np.min(temp))
print("the standard deviation of the temperature: ", np.std(temp))

The mean temerature:  33.142857142857146
the maximin temperature:  37
the minimum temperature:  29
the number of days above average temperature:  6
the difference between maximun and minimum temperature is:  8
the standard deviation of the temperature:  2.356060357495806


In [ ]:
#problem 13
sales = np.array([12000,15000,17000,14000,18000,21000,19000,22000,25000,23000,26000,28000])
print("Total sales:",np.sum(sales))
print("the average monthly sales: ", np.mean(sales))
max_sales = np.max(sales)
min_sales = np.min(sales)


Total sales: 240000
the average monthly sales:  20000.0


In [ ]:
#problem 14
marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]
])
# Total marks of every student
print("The sum of mraks of every student: ",np.sum(marks))

# Average of every student
print("The average marks of every student: ",np.mean(marks,axis =1))
# Average mark for every subject
print("The average marks of every subject: ",np.mean(marks,axis=0))
# Highest-scoring student
print("The highest scoring student: ",np.max(marks,axis=1))
# Lowest-scoring student
print("The lowest scoring student: ",np.min(marks,axis=1))
# Students whose average is greater than 80
print("The students whose average is greater than 80: ",marks[np.mean(marks,axis=1)>80])
# Overall class average
print("The overall class average: ",np.mean(marks))

The sum of mraks of every student:  1533
The average marks of every student:  [85.25 68.75 91.5  58.75 79.  ]
The average marks of every subject:  [74.  75.6 79.4 77.6]
The highest scoring student:  [90 72 95 62 82]
The lowest scoring student:  [78 65 88 55 75]
The students whose average is greater than 80:  [[78 85 90 88]
 [92 88 95 91]]
The overall class average:  76.65


In [ ]:
#problem 15
integers = np.random.randint(1,100,20)
print("20 random integers from 1 to 100 are : ", integers)

#problem 16
evens = integers[integers%2==0]
print("even numbers from the generated array: ",evens)

#problem 17
integers[integers<50]=0
print("values below 50 with 0:",integers)

#problem 18
print("ascending order: ", np.sort(integers))
print("descending order", np.sort(integers[::-1]))

#problem 19
#Find unique values and their frequencies.
print("the unique number in the array: ", np.unique(integers))
print("the frequency of the unique numbers: ", np.unique(integers,return_counts=True))


20 random integers from 1 to 100 are :  [12 98 16 30  8 57 72 52 33 57 31 47 18 65 19 54 54 69 28 13]
even numbers from the generated array:  [12 98 16 30  8 72 52 18 54 54 28]
values below 50 with 0: [ 0 98  0  0  0 57 72 52  0 57  0  0  0 65  0 54 54 69  0  0]
ascending order:  [ 0  0  0  0  0  0  0  0  0  0  0 52 54 54 57 57 65 69 72 98]
descending order [ 0  0  0  0  0  0  0  0  0  0  0 52 54 54 57 57 65 69 72 98]
the unique number in the array:  [ 0 52 54 57 65 69 72 98]
the frequency of the unique numbers:  (array([ 0, 52, 54, 57, 65, 69, 72, 98]), array([11,  1,  2,  2,  1,  1,  1,  1]))


In [ ]:
#problem 20
#Create a 5 × 5 random matrix and calculate row-wise and column-wise means.
arr = np.random.randint(0,25,(5,5))
print("row wise mean of the matrix: ", np.mean(arr,axis=1))
print("column wise mean of the matrix: ", np.mean(arr,axis=0))

row wise mean of the matrix:  [13.   9.2  9.8 11.8 17. ]
column wise mean of the matrix:  [ 8.4 18.6 11.8 14.2  7.8]


In [ ]:
#problem 21
#Take your own example to normalize an array.
import numpy as np

a = np.array([2, 4, 10])
#formula to normalise
normalized = (a - np.min(a)) / (np.max(a) - np.min(a))
print("The normalised array is: " ,normalized)

The normalised array is:  [0.   0.25 1.  ]


In [ ]:
#problem 23
#Create a NumPy array containing 100 random exam marks and determine how many students fall into the ranges 0–39, 40–59, 60–79, and 80–100.
arr = np.random.randint(1,100,100)
print("the number of students in the range of 0 to 39: ",len(arr[arr<40]))
print("the number of students in the range of 40 to 59: ",len(arr[(arr>40) & (arr<60)]))
print("the number of students in the range of 60 to 79: ",len(arr[(arr>60) & (arr<80)]))
print("the number of students in the range of 80 to 100: ",len(arr[arr>80]))

the number of students in the range of 0 to 39:  36
the number of students in the range of 40 to 59:  17
the number of students in the range of 60 to 79:  21
the number of students in the range of 80 to 100:  23


In [3]:
#problem 24
#Compare the time required to multiply 1,000,000 numbers using a Python list and a NumPy array.


import numpy as np
import time

size = 1_000_000 # 1,000,000 numbers

# Create a Python list
python_list = list(range(size))

# Create a NumPy array
numpy_array = np.arange(size)

# Measure time for Python list multiplication
start_time = time.time()
python_result = [x * 2 for x in python_list]
end_time = time.time()
python_time = end_time - start_time
print(f"Time taken for Python list multiplication: {python_time:.6f} seconds")

# Measure time for NumPy array multiplication
start_time = time.time()
numpy_result = numpy_array * 2
end_time = time.time()
numpy_time = end_time - start_time
print(f"Time taken for NumPy array multiplication: {numpy_time:.6f} seconds")

print(f"\nNumPy is approximately {python_time / numpy_time:.2f} times faster than Python lists for this operation.")

Time taken for Python list multiplication: 0.070297 seconds
Time taken for NumPy array multiplication: 0.002225 seconds

NumPy is approximately 31.60 times faster than Python lists for this operation.
