In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3])

In [ ]:
arr

array([1, 2, 3])

In [ ]:
np.ndim

<function ndim at 0x7e37c53d6eb0>

In [ ]:
np.ndim(arr)

1

In [ ]:
arr.shape

(3,)

In [ ]:
n = np.arange(0,32,2)

In [ ]:
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
print(n)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [ ]:
n.ndim

1

In [ ]:
n2 = np.arange(32,0,2)

In [ ]:
n2

array([], dtype=int64)

In [ ]:
n = np.arange(0,32,2)


In [ ]:
lspace = np.linspace(0,10,9)

In [ ]:
lspace

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [ ]:
lspace.resize(3,3)

In [ ]:
lspace

array([[ 0.  ,  1.25,  2.5 ],
       [ 3.75,  5.  ,  6.25],
       [ 7.5 ,  8.75, 10.  ]])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
num = np.matrix(([1,3,2],[4,5,6],
                [7,8,9]))

In [ ]:
np.matrix

numpy.matrix

In [ ]:
type(num)

numpy.matrix

In [ ]:
np.diag(num)

array([1, 5, 9])

In [ ]:
np.diag(num,1) #elements above the main diagnal

array([3, 6])

In [ ]:
np.diag(num,-1)#elements below the main diagonal

array([4, 8])

In [ ]:
np.diag(num,2)

array([2])

In [ ]:
np.diag(num,-2)

array([7])

In [ ]:
np.array([1,2,3]*4)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
np.repeat([1,2,3],3) # repeat the elemnts of the array

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
p=np.ones([3,3],int)

In [ ]:
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
np.vstack([p,2*p,3*p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [ ]:
np.hstack([p,2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [ ]:
np.hstack([p,2*p,3*p])

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [ ]:
print(x+y)

[5 7 9]


In [ ]:
x-y

array([-3, -3, -3])

In [ ]:
x*y

array([ 4, 10, 18])

In [ ]:
x@y # dot product

np.int64(32)

In [ ]:
print(x@y)

32


In [ ]:
x**y

array([  1,  32, 729])

In [ ]:
print(x.dot(y))

32


In [ ]:
z = np.array([y,y**2])

In [ ]:
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [ ]:
len(z) # number of rows of array

2

In [ ]:
z.shape

(2, 3)

In [ ]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [ ]:
z.T.shape

(3, 2)

In [ ]:
z.dtype

dtype('int64')

In [ ]:
z = z.astype('f')

In [ ]:
z.dtype

dtype('float32')

In [ ]:
a = np.array([1,2,3,4])
a.sum()

np.int64(10)

In [ ]:
a.max()

np.int64(4)

In [ ]:
a.min()

np.int64(1)

In [ ]:
a.mean()

np.float64(2.5)

In [ ]:
a.std()

np.float64(1.118033988749895)

In [ ]:
a.argmax() #gives the max index

np.int64(3)

In [ ]:
a.argmin() #gives the min index

np.int64(0)

In [ ]:
s = np.arange(100)

In [ ]:
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
s.reshape([10,10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
s = np.arange(6)**2

In [ ]:
s

array([ 0,  1,  4,  9, 16, 25])

In [ ]:
s = np.arange(10)**4

In [ ]:
s

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561])

In [ ]:
print(s[-1])
print(s[0])


6561
0


In [ ]:
s[1:5]

array([  1,  16,  81, 256])

In [ ]:
s[1:5:2]

array([ 1, 81])

In [ ]:
s[-5::-2]

array([625,  81,   1])

In [ ]:
r = np.arange(100)
r =r.reshape([10,10])
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
r[3, 4]

np.int64(34)

In [ ]:
r[2, 1:5]

array([21, 22, 23, 24])

In [ ]:
r[:3,:-1] #r[row,cloumn]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [20, 21, 22, 23, 24, 25, 26, 27, 28]])

In [ ]:
r[r>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
       65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
       82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
       99])

In [ ]:
r[r>40] = 40

In [ ]:
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40]])

In [ ]:
r2 = r[:3,:3]

In [ ]:
r2

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [ ]:
r2[:] = 0

In [ ]:
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
r

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40]])

In [ ]:
r3 = r[1:3,:3]

In [ ]:
r3

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
r_copy = r.copy()
r_copy[:] = 10
r_copy

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [ ]:
ran = np.random.randint(0,10,(4,3)) # ( ini range, final range, matrix coloumns needed)

In [ ]:
ran

array([[3, 6, 4],
       [5, 6, 9],
       [8, 4, 8],
       [1, 8, 0]])

In [ ]:
for i in ran:
  print(i)

[3 6 4]
[5 6 9]
[8 4 8]
[1 8 0]


In [ ]:
for i, row in enumerate(ran):
  print('row',i,'is',row)

row 0 is [3 6 4]
row 1 is [5 6 9]
row 2 is [8 4 8]
row 3 is [1 8 0]


In [ ]:
ran2 = ran**3

In [ ]:
ran2

array([[ 27, 216,  64],
       [125, 216, 729],
       [512,  64, 512],
       [  1, 512,   0]])

In [ ]:
for i, j in zip(ran,ran2):
  print(i+j)

[ 30 222  68]
[130 222 738]
[520  68 520]
[  2 520   0]


In [ ]:
marks = np.array([[50,60,20],
                 [67,89,9],
                 [12,34,56]])

In [ ]:
np.sum(marks,axis=1)

array([130, 165, 102])

In [ ]:
np.mean(marks,axis=0)

array([43.        , 61.        , 28.33333333])

In [ ]:
np.max(marks)

np.int64(89)

In [ ]:
np.min(marks)

np.int64(9)